/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DamageList.java
 *
 * Created on Jun 27, 2015, 8:36:32 PM
 */
package inventorymanagement;

import BusinessLayer.DamageBl;
import BusinessLayer.ItemBl;
import ObjectFactory.DamageOF;
import ObjectFactory.ItemOF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chhabi
 */
public class DamageList extends javax.swing.JInternalFrame {

    /** Creates new form DamageList */
    public DamageList() {
        initComponents();
        
        // item name in combo box
        ItemBl it = new ItemBl();
        try{
            ArrayList<ItemOF> itm = it.getItemList();
            for( int i=0; i<itm.size(); ++i){
                cmbItemName.addItem(itm.get(i).getItem_name());
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        damage = new DamageOF();
        bldamage = new DamageBl();
        DefaultTableModel dtm = new DefaultTableModel();
        try{

            dtm.addColumn("Damage Id");
            dtm.addColumn("Damage Name");
            dtm.addColumn("Damage Quantity");
            dtm.addColumn("Damage Date");
            dtm.addColumn("Damage Detail");
            dtm.addColumn("Item Name");
                        
            ArrayList<DamageOF> damages = bldamage.getdamageList();
            for(int i=0; i<damages.size(); ++i ){
              Object[] data = { damages.get(i).getDamage_id(), damages.get(i).getDamage_name(), damages.get(i).getDamage_quantity(), damages.get(i).getDamage_date(), damages.get(i).getDamage_detail(), damages.get(i).getItem_name() };
              dtm.addRow(data);
            }
            tblDamageList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDamageList = new javax.swing.JTable();
        txtSearchDamage = new javax.swing.JTextField();
        btnSeachDamage = new javax.swing.JButton();
        btnEditSelected = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtDamageQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDamageDate = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDamageId = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDamageDetail = new javax.swing.JTextArea();
        txtDamageName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnDamageUpdate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnDamageDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbItemName = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Damage Items Detail");

        tblDamageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblDamageList);

        btnSeachDamage.setText("Search");
        btnSeachDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachDamageActionPerformed(evt);
            }
        });

        btnEditSelected.setText("Edit the Selected ");
        btnEditSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSelectedActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Damage Items List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeachDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeachDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchDamage))
                .addGap(18, 18, 18)
                .addComponent(btnEditSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setText("Damage Quantity : ");

        jLabel7.setText("Damage Detail : ");

        jLabel6.setText("Damage Date : ");

        txtDamageId.setEditable(false);

        txtDamageDetail.setColumns(20);
        txtDamageDetail.setRows(5);
        jScrollPane2.setViewportView(txtDamageDetail);

        jLabel3.setText("Damage Id : ");

        btnDamageUpdate.setText("Update");
        btnDamageUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDamageUpdateActionPerformed(evt);
            }
        });

        jLabel4.setText("Damage Name : ");

        btnDamageDelete.setText("Delete");
        btnDamageDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDamageDeleteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit the Selected Damage Item");

        jLabel8.setText("Item Name : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDamageId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(35, 35, 35)
                                .addComponent(cmbItemName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDamageName)))
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(23, 23, 23)
                        .addComponent(txtDamageDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnDamageUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDamageQuantity)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnDamageDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(220, 220, 220))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDamageId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDamageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDamageQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtDamageDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDamageUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDamageDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSeachDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachDamageActionPerformed
// TODO add your handling code here:
    try{
        damage.setDamage_name(txtSearchDamage.getText());
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Damage Id");
        dtm.addColumn("Damage Name");
        dtm.addColumn("Damage Quantity");
        dtm.addColumn("Damage Date");
        dtm.addColumn("Damage Detail");    
        dtm.addColumn("Item Name");

        bldamage = new DamageBl(damage);
        ArrayList<DamageOF> damages = bldamage.searchdamage();
            if(damages.size() > 0){
                for( int i=0; i<damages.size(); i++){
                    Object[] data = { damages.get(i).getDamage_id(), damages.get(i).getDamage_name(), damages.get(i).getDamage_quantity(), damages.get(i).getDamage_date(), damages.get(i).getDamage_detail(), damages.get(i).getItem_name()};
                    dtm.addRow(data);                    
                }
                tblDamageList.setModel(dtm);

            } else {
                Object[] data = {"","","","",""};
                JOptionPane.showMessageDialog(this, "No Damage Item FOund");
                tblDamageList.setModel(dtm);
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }
}//GEN-LAST:event_btnSeachDamageActionPerformed

private void btnEditSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectedActionPerformed
// TODO add your handling code here:
    try{
        String dId      = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 0).toString();
        String dName    = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 1).toString();
        String dQty     = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 2).toString();
        String dDate    = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 3).toString();
        String dDetail  = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 4).toString();
        String itemName = tblDamageList.getValueAt(tblDamageList.getSelectedRow(), 5).toString();
        
        txtDamageId.setText(dId);
        txtDamageName.setText(dName);
        txtDamageQuantity.setText(dQty);
   
        // Date load in edit form
        SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd");
        txtDamageDate.setDate((Date)oFormat.parse(dDate));
        
        txtDamageDetail.setText(dDetail);
        cmbItemName.setSelectedItem(itemName);
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
    
}//GEN-LAST:event_btnEditSelectedActionPerformed

private void btnDamageUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDamageUpdateActionPerformed
// TODO add your handling code here:
    try{
       damage = new DamageOF();
       damage.setDamage_id(Integer.parseInt(txtDamageId.getText()));
       damage.setDamage_name( new String(txtDamageName.getText())); 
       damage.setDamage_quantity(Integer.parseInt(txtDamageQuantity.getText()));
       
       Date dtt = txtDamageDate.getDate();
       SimpleDateFormat ftt = new SimpleDateFormat("yyyy-MM-dd");
       damage.setDamage_date(ftt.format(dtt).toString());
       
       damage.setDamage_detail( new String(txtDamageDetail.getText()));
       damage.setItem_name(cmbItemName.getSelectedItem().toString());
       
       bldamage = new DamageBl(damage);
       if(bldamage.updatedamage()){
           JOptionPane.showMessageDialog(this, "Damage Updated Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           DashBoard.dashBoard.add( new CategoryList());
           
       }else{
           JOptionPane.showMessageDialog(this, "Unable to Update Damage", "Error Occured", JOptionPane.ERROR_MESSAGE);
       }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }    
}//GEN-LAST:event_btnDamageUpdateActionPerformed

private void btnDamageDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDamageDeleteActionPerformed
// TODO add your handling code here:
    try{
        damage = new DamageOF();
        damage.setDamage_id(Integer.parseInt(txtDamageId.getText()));
        bldamage = new DamageBl(damage);
        if(bldamage.deletedamage()){
            JOptionPane.showMessageDialog(this, "Damage Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            DashBoard.dashBoard.add( new CategoryList());
        }else{
            JOptionPane.showMessageDialog(this, "Unabale to Delete Damage", "Error Occured", JOptionPane.ERROR_MESSAGE );
        }
    }catch( Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
    
}//GEN-LAST:event_btnDamageDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDamageDelete;
    private javax.swing.JButton btnDamageUpdate;
    private javax.swing.JButton btnEditSelected;
    private javax.swing.JButton btnSeachDamage;
    private javax.swing.JComboBox cmbItemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDamageList;
    private com.toedter.calendar.JDateChooser txtDamageDate;
    private javax.swing.JTextArea txtDamageDetail;
    private javax.swing.JTextField txtDamageId;
    private javax.swing.JTextField txtDamageName;
    private javax.swing.JTextField txtDamageQuantity;
    private javax.swing.JTextField txtSearchDamage;
    // End of variables declaration//GEN-END:variables
    private DamageOF damage;
    private DamageBl bldamage;
}
