/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DbBackUp.java
 *
 * Created on Jul 10, 2015, 10:14:29 PM
 */
package inventorymanagement;

import DatabaseLayer.DataBase;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author chhabi
 */
public class DbBackUp extends javax.swing.JInternalFrame {

    /** Creates new form DbBackUp */
    public DbBackUp() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDbbackUp = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Want to Back Up Database ?");

        btnDbbackUp.setText("Keep BacUp of Database");
        btnDbbackUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDbbackUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDbbackUp, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnDbbackUp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnDbbackUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDbbackUpActionPerformed
// TODO add your handling code here:
        try {
            new DataBase().DbBackUp();
            JOptionPane.showMessageDialog(this, "Backup Sucessfully");
        } catch (Exception ex) {
            Logger.getLogger(DbBackUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Backup Error");
        }
    
}//GEN-LAST:event_btnDbbackUpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDbbackUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
