/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemList.java
 *
 * Created on Jul 7, 2015, 8:43:52 PM
 */
package inventorymanagement;

import BusinessLayer.CategoryBl;
import BusinessLayer.ItemBl;
import BusinessLayer.SupplierBl;
import DatabaseLayer.GlobalConnection;
import ObjectFactory.CategoryOF;
import ObjectFactory.ItemOF;
import ObjectFactory.SupplierOF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chhabi
 */
public class ItemList extends javax.swing.JInternalFrame {
    
    GlobalConnection db = new GlobalConnection();
    ArrayList<String> ar = new ArrayList<String>();
    
    /** Creates new form ItemList */
    public ItemList(){
        initComponents();
        
        // category name in combo box
        CategoryBl cb = new CategoryBl();
        try{
            ArrayList<CategoryOF> ct = cb.getcategoryList();
            for( int i=0; i<ct.size(); ++i){
                cmbCategoryName.addItem(ct.get(i).getCat_name());
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        // supplier name in combo box
        SupplierBl sb = new SupplierBl();
        try{
            ArrayList<SupplierOF> ct = sb.getsupplierList();
            for( int i=0; i<ct.size(); ++i){
                cmbSupplierName.addItem(ct.get(i).getSupplier_name());
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        item   = new ItemOF();
        blitem = new ItemBl();
        DefaultTableModel dtm = new DefaultTableModel();
        try{
            dtm.addColumn("Id");
            dtm.addColumn("Name");
            dtm.addColumn("Category Name");
            dtm.addColumn("Supplier Name");
            dtm.addColumn("Rate");
            dtm.addColumn("Quantity");
            dtm.addColumn("Order Date");
            dtm.addColumn("Supplied Date");
            dtm.addColumn("Detail");
                                    
            ArrayList<ItemOF> items = blitem.getItemList();
            for(int i=0; i<items.size(); ++i ){
              Object[] data = { items.get(i).getItem_id(), items.get(i).getItem_name(), items.get(i).getCat_name(), items.get(i).getSupplier_name(), items.get(i).getItem_rate(), items.get(i).getItem_quantity(), items.get(i).getItem_order_date(), items.get(i).getItem_supplied_date(), items.get(i).getItem_detail() };
              dtm.addRow(data);
            }
            tblItemList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSelectedItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemList = new javax.swing.JTable();
        btnItemSearch = new javax.swing.JButton();
        txtSearchItem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtItemQuantity = new javax.swing.JTextField();
        cmbCategoryName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbSupplierName = new javax.swing.JComboBox();
        txtItemRate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtItemOrderDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtItemId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemSuppliedDate = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtItemDetail = new javax.swing.JTextArea();
        btnUpdateItem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnSelectedItem.setText("Edit Selected Item");
        btnSelectedItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedItemActionPerformed(evt);
            }
        });

        tblItemList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblItemList);

        btnItemSearch.setText("Search");
        btnItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Items List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelectedItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Item Quantity : ");

        jLabel5.setText("Item Rate : ");

        jLabel3.setText("Category Name :");

        jLabel4.setText("Supplier Name :");

        jLabel7.setText("Order Date : ");

        jLabel10.setText("Item Id : ");

        txtItemId.setEditable(false);

        jLabel11.setText("Item Name : ");

        jLabel9.setText("Item Detail : ");

        txtItemDetail.setColumns(20);
        txtItemDetail.setRows(5);
        jScrollPane2.setViewportView(txtItemDetail);

        btnUpdateItem.setText("Update");
        btnUpdateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemActionPerformed(evt);
            }
        });

        jLabel8.setText("Supplied Date : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit the Selected Item");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(cmbSupplierName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCategoryName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtItemQuantity)
                    .addComponent(txtItemName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemRate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtItemOrderDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addComponent(txtItemOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addComponent(btnUpdateItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(194, 194, 194))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSelectedItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedItemActionPerformed
// TODO add your handling code here:
    try{
    
    String itemId    = tblItemList.getValueAt(tblItemList.getSelectedRow(), 0).toString();
    String itemName  = tblItemList.getValueAt(tblItemList.getSelectedRow(), 1).toString();
    String catName   = tblItemList.getValueAt(tblItemList.getSelectedRow(), 2).toString();
    String supName   = tblItemList.getValueAt(tblItemList.getSelectedRow(), 3).toString();
    String itemRate  = tblItemList.getValueAt(tblItemList.getSelectedRow(), 4).toString();
    String itemQty   = tblItemList.getValueAt(tblItemList.getSelectedRow(), 5).toString();
    String odate     = tblItemList.getValueAt(tblItemList.getSelectedRow(), 6).toString();
    String sdate     = tblItemList.getValueAt(tblItemList.getSelectedRow(), 7).toString();
    String itemDetail = tblItemList.getValueAt(tblItemList.getSelectedRow(), 8).toString();
        
    txtItemId.setText(itemId);
    txtItemName.setText(itemName);
    cmbCategoryName.setSelectedItem(catName);
    cmbSupplierName.setSelectedItem(supName);
    txtItemRate.setText(itemRate);
    txtItemQuantity.setText(itemQty);
    
    // Date load in edit form
    SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd");
    txtItemOrderDate.setDate((Date)oFormat.parse(odate));
    
    // Date load in edit form
    SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
    txtItemSuppliedDate.setDate((Date)sFormat.parse(sdate));
    
    txtItemDetail.setText(itemDetail);
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
}//GEN-LAST:event_btnSelectedItemActionPerformed

private void btnUpdateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemActionPerformed
// TODO add your handling code here:
    try {
       item = new ItemOF();
       item.setItem_id(Integer.parseInt(txtItemId.getText()));
       item.setItem_name( new String(txtItemName.getText())); 
       item.setCat_name(cmbCategoryName.getSelectedItem().toString());
       item.setSupplier_name(cmbSupplierName.getSelectedItem().toString());
       item.setItem_rate(Integer.parseInt(txtItemRate.getText()));
       item.setItem_quantity(Integer.parseInt(txtItemQuantity.getText()));
       
       Date dtt = txtItemOrderDate.getDate();
       SimpleDateFormat ftt = new SimpleDateFormat("yyyy-MM-dd");
       item.setItem_order_date(ftt.format(dtt).toString());

       Date ddd = txtItemSuppliedDate.getDate();
       SimpleDateFormat fff = new SimpleDateFormat("yyyy-MM-dd");
       item.setItem_supplied_date(fff.format(ddd).toString());
       
       item.setItem_detail( new String(txtItemDetail.getText()));
       
       blitem = new ItemBl(item);   
       if(blitem.updateItem()){
           JOptionPane.showMessageDialog(this, "Item Updated Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           DashBoard.dashBoard.add( new CategoryList());
           
            }else{
                JOptionPane.showMessageDialog(this, "Unable to Update Item", "Error Occured", JOptionPane.ERROR_MESSAGE);
            }
       
       } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
       }
    
}//GEN-LAST:event_btnUpdateItemActionPerformed

private void btnItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSearchActionPerformed
// TODO add your handling code here:
        try{
            item.setItem_name(txtSearchItem.getText().toString());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Id");
            dtm.addColumn("Name");            
            dtm.addColumn("Rate");
            dtm.addColumn("Quantity");
            dtm.addColumn("Order Date");
            dtm.addColumn("Supplied Date");
            dtm.addColumn("Detail");
            dtm.addColumn("Category Name");
            dtm.addColumn("Supplier Name");
           
            blitem = new ItemBl(item);
            ArrayList<ItemOF>items = blitem.searchItem();
                if(items.size() > 0){
                    for( int i=0; i<items.size(); i++){
                        Object[] data = { items.get(i).getItem_id(), items.get(i).getItem_name(),  items.get(i).getItem_rate(), items.get(i).getItem_quantity(), items.get(i).getItem_order_date(), items.get(i).getItem_supplied_date(), items.get(i).getItem_detail(),items.get(i).getCat_name(), items.get(i).getSupplier_name() };
                        dtm.addRow(data);                    
                    }
                    tblItemList.setModel(dtm);
                
                }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }
}//GEN-LAST:event_btnItemSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemSearch;
    private javax.swing.JButton btnSelectedItem;
    private javax.swing.JButton btnUpdateItem;
    private javax.swing.JComboBox cmbCategoryName;
    private javax.swing.JComboBox cmbSupplierName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItemList;
    private javax.swing.JTextArea txtItemDetail;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtItemName;
    private com.toedter.calendar.JDateChooser txtItemOrderDate;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtItemRate;
    private com.toedter.calendar.JDateChooser txtItemSuppliedDate;
    private javax.swing.JTextField txtSearchItem;
    // End of variables declaration//GEN-END:variables
    private ItemOF item;
    private ItemBl blitem;
}
