/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemRegister.java
 *
 * Created on Jun 27, 2015, 11:14:49 PM
 */
package inventorymanagement;

import BusinessLayer.CategoryBl;
import BusinessLayer.ItemBl;
import BusinessLayer.SupplierBl;
import ObjectFactory.CategoryOF;
import ObjectFactory.ItemOF;
import ObjectFactory.SupplierOF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author chhabi
 */
public class ItemRegister extends javax.swing.JInternalFrame {

    /** Creates new form ItemRegister */
    public ItemRegister() {
        initComponents();
      
      // Get category name in comobox  
      CategoryBl catBl = new CategoryBl();
      try {          
           ArrayList<CategoryOF> catName = catBl.getcategoryList();
           for(int i=0; i<catName.size(); ++i )           
           {     
             cmbCategory.addItem(catName.get(i).getCat_name());             
           }
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "No Category Name.\n" + e);
      }
      
      // Get supplier name in combo box
      SupplierBl supBl = new SupplierBl();
      try {          
           ArrayList<SupplierOF> supplierName = supBl.getsupplierList();
           for(int i=0; i<supplierName.size(); ++i )           
           {     
             cmbSupplier.addItem(supplierName.get(i).getSupplier_name());             
           }
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "No Supplier Name.\n" + e);
      }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemRate = new javax.swing.JTextField();
        txtItemQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemOrderDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtItemDetail = new javax.swing.JTextArea();
        btnItemRegister = new javax.swing.JButton();
        btnItemReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox();
        cmbSupplier = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtItemSuppliedDate = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Item Register Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Register New Item");

        jLabel2.setText("Item Name  : ");

        jLabel3.setText("Item Rate  : ");

        jLabel4.setText("Item Quantity  : ");

        jLabel5.setText("Item Order Date  : ");

        txtItemOrderDate.setDateFormatString("yyyy-MM-dd");

        jLabel6.setText("Item Supplied Date  : ");

        jLabel7.setText("Item Detail  : ");

        txtItemDetail.setColumns(20);
        txtItemDetail.setRows(5);
        jScrollPane1.setViewportView(txtItemDetail);

        btnItemRegister.setText("Register");
        btnItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemRegisterActionPerformed(evt);
            }
        });

        btnItemReset.setText("Reset");
        btnItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemResetActionPerformed(evt);
            }
        });

        jLabel8.setText("Category Name  : ");

        jLabel9.setText("Supplier Name  : ");

        txtItemSuppliedDate.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnItemRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtItemQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtItemRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(cmbSupplier, 0, 254, Short.MAX_VALUE)
                            .addComponent(txtItemOrderDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addGap(166, 166, 166))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtItemOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnItemRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemRegisterActionPerformed
// TODO add your handling code here:
    try{
        
        String errorMsg = "";
        if("".equals(txtItemName.getText())){
          errorMsg +=  "Item Name cannot be empty \n";
        }
        if("".equals(txtItemRate.getText())){
          errorMsg +=  "Item Rate cannot be empty \n";
        }
        if("".equals(txtItemQuantity.getText())){
          errorMsg += "Item Quantity cannot be emty \n";
        }        
        
        else{
            Validation v = new Validation();
            
            if (!v.checkValidation("text", txtItemName.getText()))
                errorMsg += "Item Name supports only Character \n";                           
            if (!v.checkValidation("number", txtItemRate.getText()))
                errorMsg += "Item Rate supports only Number \n";
            if (!v.checkValidation("number", txtItemQuantity.getText()))
                errorMsg += "Item Quantity supports only Number \n";            
                           
        }
      if(errorMsg.isEmpty()){  
        
        item = new ItemOF();
        item.setItem_id(0);
        item.setItem_name(txtItemName.getText());

        item.setItem_rate(Integer.parseInt(txtItemRate.getText()));
        item.setItem_quantity(Integer.parseInt(txtItemQuantity.getText()));

        Date od = txtItemOrderDate.getDate();
        SimpleDateFormat order_date =new SimpleDateFormat("yyyy-MM-dd");
        item.setItem_order_date(order_date.format(od).toString());

        Date sd = txtItemSuppliedDate.getDate();
        SimpleDateFormat supplied_date = new SimpleDateFormat("yyyy-MM-dd");
        item.setItem_supplied_date(supplied_date.format(sd).toString());

       //user.setUser_type(cmbRegisterUserType.getSelectedItem().toString());
        item.setCat_name(cmbCategory.getSelectedItem().toString());
        item.setSupplier_name(cmbSupplier.getSelectedItem().toString());

        item.setItem_detail(txtItemDetail.getText());

        blItem = new ItemBl(item);
        if(blItem.insertItem()){
          JOptionPane.showMessageDialog(this, "Item Created Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
        }else{
          JOptionPane.showMessageDialog(this, "Unable to add Item", "Error Occured", JOptionPane.ERROR_MESSAGE);
        }
      
      }else{
          JOptionPane.showMessageDialog(this, errorMsg, "Error Occured", JOptionPane.ERROR_MESSAGE);
      } 
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured here", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnItemRegisterActionPerformed

private void btnItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemResetActionPerformed
// TODO add your handling code here:
    txtItemName.setText("");
    cmbCategory.setSelectedIndex(0);
    cmbSupplier.setSelectedIndex(0);    
    txtItemRate.setText("");
    txtItemQuantity.setText("");
    txtItemOrderDate.setDate(null);
    txtItemSuppliedDate.setDate(null);
    txtItemDetail.setText("");
    
}//GEN-LAST:event_btnItemResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemRegister;
    private javax.swing.JButton btnItemReset;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtItemDetail;
    private javax.swing.JTextField txtItemName;
    private com.toedter.calendar.JDateChooser txtItemOrderDate;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtItemRate;
    private com.toedter.calendar.JDateChooser txtItemSuppliedDate;
    // End of variables declaration//GEN-END:variables
    private ItemBl blItem;
    private ItemOF item;
}
