/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SupplierList.java
 *
 * Created on Jun 25, 2015, 10:42:46 PM
 */
package inventorymanagement;

import BusinessLayer.SupplierBl;
import ObjectFactory.SupplierOF;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chhabi
 */
public class SupplierList extends javax.swing.JInternalFrame {

    /** Creates new form SupplierList */
    public SupplierList() {
        initComponents();
        supplier = new SupplierOF();
        blsupplier = new SupplierBl();
        DefaultTableModel dtm = new DefaultTableModel();
        try{

            dtm.addColumn("Supplier Id");
            dtm.addColumn("Supplier Name");
            dtm.addColumn("Supplier Phone");
            dtm.addColumn("Supplier Address");
            dtm.addColumn("Supplier Detail");
                        
            ArrayList<SupplierOF> suppliers = blsupplier.getsupplierList();
            for(int i=0; i<suppliers.size(); ++i ){
              Object[] data = { suppliers.get(i).getSupplier_id(), suppliers.get(i).getSupplier_name(), suppliers.get(i).getSupplier_phone(), suppliers.get(i).getSupplier_address(), suppliers.get(i).getSupplier_detail()};
              dtm.addRow(data);
            }
            tblSupplierList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplierList = new javax.swing.JTable();
        txtSearchSupplier = new javax.swing.JTextField();
        btnSupplierSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSupplierPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSupplierDetail = new javax.swing.JTextArea();
        btnSupplierUpdate = new javax.swing.JButton();
        btnSupplierDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Supplier List");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Supplier List");

        jButton1.setText("Edit Selected Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblSupplierList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblSupplierList);

        btnSupplierSearch.setText("Search Supplier");
        btnSupplierSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit the Selected Supplier");

        jLabel3.setText("Supplier Id : ");

        txtSupplierId.setEditable(false);

        jLabel4.setText("Supplier Name : ");

        jLabel5.setText("Supplier Phone : ");

        jLabel6.setText("Supplier Address : ");

        jLabel7.setText("Supplier Detail : ");

        txtSupplierDetail.setColumns(20);
        txtSupplierDetail.setRows(5);
        jScrollPane2.setViewportView(txtSupplierDetail);

        btnSupplierUpdate.setText("Update");
        btnSupplierUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierUpdateActionPerformed(evt);
            }
        });

        btnSupplierDelete.setText("Delete");
        btnSupplierDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSupplierSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSupplierAddress)
                                .addComponent(txtSupplierPhone)
                                .addComponent(txtSupplierName)
                                .addComponent(txtSupplierId, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(676, 676, 676)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSupplierDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupplierSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnSupplierUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupplierDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    txtSupplierId.setText(tblSupplierList.getModel().getValueAt(tblSupplierList.getSelectedRow(), 0).toString());
    txtSupplierName.setText(tblSupplierList.getModel().getValueAt(tblSupplierList.getSelectedRow(), 1).toString());
    txtSupplierPhone.setText(tblSupplierList.getModel().getValueAt(tblSupplierList.getSelectedRow(), 2).toString());
    txtSupplierAddress.setText(tblSupplierList.getModel().getValueAt(tblSupplierList.getSelectedRow(), 3).toString());
    txtSupplierDetail.setText(tblSupplierList.getModel().getValueAt(tblSupplierList.getSelectedRow(), 4).toString());
}//GEN-LAST:event_jButton1ActionPerformed

private void btnSupplierUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierUpdateActionPerformed
// TODO add your handling code here:
    try{
      supplier = new SupplierOF();
      supplier.setSupplier_id(Integer.parseInt(txtSupplierId.getText()));
      supplier.setSupplier_name(txtSupplierName.getText());
      supplier.setSupplier_phone(txtSupplierPhone.getText());
      supplier.setSupplier_address(txtSupplierAddress.getText());
      supplier.setSupplier_detail(txtSupplierDetail.getText());
      blsupplier = new SupplierBl(supplier);
      if(blsupplier.updatesupplier()){
        JOptionPane.showMessageDialog(this, "Supplier Updated Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        DashBoard.dashBoard.add( new SupplierList());
      }else{
        JOptionPane.showMessageDialog(this, "Unable to Update Supplier", "Error Occured", JOptionPane.ERROR_MESSAGE);
      }
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnSupplierUpdateActionPerformed

private void btnSupplierDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDeleteActionPerformed
// TODO add your handling code here:
     try {
        supplier = new SupplierOF();
        supplier.setSupplier_id(Integer.parseInt(txtSupplierId.getText()));
        blsupplier = new SupplierBl(supplier);
        if(blsupplier.deletesupplier()){
          JOptionPane.showMessageDialog(this, "Supplier Deleted Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);  
          this.dispose();
          DashBoard.dashBoard.add( new SupplierList());
        }else{
          JOptionPane.showMessageDialog(this, "Unable to Delete Supplier", "Error Occured", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnSupplierDeleteActionPerformed

private void btnSupplierSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierSearchActionPerformed
// TODO add your handling code here:
     try{
            supplier.setSupplier_name(txtSearchSupplier.getText());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Supplier Id");
            dtm.addColumn("Supplier Name");
            dtm.addColumn("Supplier Phone");
            dtm.addColumn("Supplier Address");
            dtm.addColumn("Supplier Detail");            
            
            blsupplier = new SupplierBl(supplier);
            ArrayList<SupplierOF> suppliers = blsupplier.searchsupplier();
                if(suppliers.size() > 0){
                    for( int i=0; i<suppliers.size(); i++){
                        Object[] data = { suppliers.get(i).getSupplier_id(), suppliers.get(i).getSupplier_name(), suppliers.get(i).getSupplier_phone(), suppliers.get(i).getSupplier_address(),suppliers.get(i).getSupplier_detail() };
                        dtm.addRow(data);                    
                    }
                    tblSupplierList.setModel(dtm);
                
                } else {
                    Object[] data = {"","","","",""};
                    JOptionPane.showMessageDialog(this, "No Supplier FOund");
                    tblSupplierList.setModel(dtm);
                }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }   
}//GEN-LAST:event_btnSupplierSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSupplierDelete;
    private javax.swing.JButton btnSupplierSearch;
    private javax.swing.JButton btnSupplierUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSupplierList;
    private javax.swing.JTextField txtSearchSupplier;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextArea txtSupplierDetail;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierPhone;
    // End of variables declaration//GEN-END:variables
    private SupplierOF supplier;
    private SupplierBl blsupplier;
}
