/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserList.java
 *
 * Created on Jun 23, 2015, 10:41:43 PM
 */
package inventorymanagement;

import BusinessLayer.UserBl;
import ObjectFactory.UserOF;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chhabi
 */
public class UserList extends javax.swing.JInternalFrame {

    /** Creates new form UserList */
    public UserList() {
        initComponents();
        user = new UserOF();
        blUser = new UserBl();
        DefaultTableModel dtm = new DefaultTableModel();
        try{

            dtm.addColumn("User Id");
            dtm.addColumn("User Name");
            //dtm.addColumn("User Password");
            dtm.addColumn("User Email");
            dtm.addColumn("User Type");

            ArrayList<UserOF> users = blUser.getUserList();
            for(int i=0; i<users.size(); ++i ){
              Object[] data = { users.get(i).getUser_id(), users.get(i).getUser_name(),/*  users.get(i).getUser_password(),*/ users.get(i).getUser_email(), users.get(i).getUser_type()};
              dtm.addRow(data);
            }
            tblUsersList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public UserOF getUser() {
        return user;
    }

    public void setUser(UserOF user) {
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEditSelectedUser = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox();
        btnUserUpdate = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        txtUserId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        btnUserSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Users List ");
        setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit Selected User's Detail");

        btnEditSelectedUser.setText("Edit Selected User");
        btnEditSelectedUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSelectedUserActionPerformed(evt);
            }
        });

        jLabel3.setText("User Name : ");

        jLabel4.setText("User Email : ");

        jLabel5.setText("User Type : ");

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guest", "Admin" }));
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        btnUserUpdate.setText("Update");
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });

        btnUserDelete.setText("Delete");
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });

        txtUserId.setEditable(false);

        jLabel6.setText("User Id : ");

        txtUserSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserSearchKeyReleased(evt);
            }
        });

        btnUserSearch.setText("Search");
        btnUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSearchActionPerformed(evt);
            }
        });

        tblUsersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsersList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Users List ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(135, 135, 135)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditSelectedUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addGap(43, 43, 43))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserId)
                            .addComponent(btnUserDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUserUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserEmail)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(txtUserName)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtUserSearch)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnUserUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnUserDelete)
                        .addContainerGap(280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditSelectedUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnEditSelectedUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectedUserActionPerformed
// TODO add your handling code here:
    txtUserId.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 0).toString());
    txtUserName.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 1).toString());
    txtUserEmail.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 2).toString());
    cmbUserType.setSelectedItem(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 3).toString());
}//GEN-LAST:event_btnEditSelectedUserActionPerformed

private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
// TODO add your handling code here:
    try{
      user = new UserOF();
      user.setUser_id(Integer.parseInt(txtUserId.getText()));
      user.setUser_name( new String(txtUserName.getText()));
      user.setUser_email( new String(txtUserEmail.getText()));
      user.setUser_type(cmbUserType.getSelectedItem().toString());
      blUser = new UserBl(user);
      if(blUser.updateUser()){
        JOptionPane.showMessageDialog(this, "User Updated Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
      
        this.dispose();
        DashBoard.dashBoard.add( new UserList());
      }else{
        JOptionPane.showMessageDialog(this, "Unable to update user", "Error Occured", JOptionPane.ERROR_MESSAGE);
      }
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnUserUpdateActionPerformed

private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
// TODO add your handling code here:
    try{
        user = new UserOF();
        user.setUser_id(Integer.parseInt(txtUserId.getText()));
        blUser = new UserBl(user);
        if(blUser.deleteUser()){
            JOptionPane.showMessageDialog(null, "User Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            DashBoard.dashBoard.add( new UserList());
        }else{
            JOptionPane.showMessageDialog(this, "Unabale to Delete User", "Error Occured", JOptionPane.ERROR_MESSAGE );
        }
    }catch( Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnUserDeleteActionPerformed

private void txtUserSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSearchKeyReleased
// TODO add your handling code here
//    try{
//      user = new UserOF();
//      user.setUser_id(Integer.parseInt(txtUserId.getText()));
//      user.setUser_name( new String(txtUserName.getText()));
//      user.setUser_email( new String(txtUserEmail.getText()));
//      user.setUser_type(cmbUserType.getSelectedItem().toString());
//      blUser = new UserBl(user);
//      ArrayList<UserOF> users = blUser.searchUser();
//        for(int i=0; i<users.size(); ++i ){
//          Object[] data = { users.get(i).getUser_id(), users.get(i).getUser_name(), users.get(i).getUser_email(), users.get(i).getUser_type()};
//            txtUserId.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 0).toString());
//            txtUserName.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 1).toString());
//            txtUserEmail.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 2).toString());
//            cmbUserType.setSelectedItem(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 3).toString());
//        }
//    }catch(Exception ex){
//      JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
//    }
}//GEN-LAST:event_txtUserSearchKeyReleased

private void btnUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSearchActionPerformed
// TODO add your handling code here:        
        //initComponents();
        try{
            user.setUser_name(txtUserSearch.getText());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("User Id");
            dtm.addColumn("User Name");
            dtm.addColumn("User Email");
            dtm.addColumn("User Type");
            
            blUser = new UserBl(user);
            ArrayList<UserOF> users = blUser.searchUser();
                if(users.size() > 0){
                    for( int i=0; i<users.size(); i++){
                        Object[] data = { users.get(i).getUser_id(), users.get(i).getUser_name(), users.get(i).getUser_email(), users.get(i).getUser_type()};
                        dtm.addRow(data);                    
                    }
                    tblUsersList.setModel(dtm);
                
                } else {
                    Object[] data = {"","","",""};
                    JOptionPane.showMessageDialog(this, "NO user FOund");
                    tblUsersList.setModel(dtm);
                }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }                
}//GEN-LAST:event_btnUserSearchActionPerformed

private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbUserTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditSelectedUser;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsersList;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
    private UserOF user;
    private UserBl blUser;
    
}
