/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserRegister.java
 *
 * Created on Jun 23, 2015, 10:07:01 PM
 */
package inventorymanagement;

import BusinessLayer.UserBl;
import ObjectFactory.UserOF;
import javax.swing.JOptionPane;

/**
 *
 * @author chhabi
 */
public class UserRegister extends javax.swing.JInternalFrame {

    /** Creates new form UserRegister */
    public UserRegister() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRegisterUserName = new javax.swing.JTextField();
        txtRegisterUserEmail = new javax.swing.JTextField();
        cmbRegisterUserType = new javax.swing.JComboBox();
        btnRegisterUser = new javax.swing.JButton();
        btnResetUser = new javax.swing.JButton();
        txtRegisterUserPassword = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("User Register Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Register New User For System");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("User Name : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Password : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Email : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("User Type : ");

        cmbRegisterUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Guest" }));

        btnRegisterUser.setText("Registern User");
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserActionPerformed(evt);
            }
        });

        btnResetUser.setText("Reset Fields");
        btnResetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btnRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResetUser, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRegisterUserPassword)
                                    .addComponent(cmbRegisterUserType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRegisterUserEmail)
                                    .addComponent(txtRegisterUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRegisterUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRegisterUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtRegisterUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbRegisterUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserActionPerformed
    
    try{
        String errorMsg = "";
        if("".equals(txtRegisterUserName.getText())){
          errorMsg +=  "User Name cannot be empty \n";
        }
        if("".equals(txtRegisterUserPassword.getText())){
          errorMsg +=  "Password cannot be empty \n";
        }
        if("".equals(txtRegisterUserEmail.getText())){
          errorMsg += "Email cannot be emty \n";
        }
        
        else{
            Validation v = new Validation();
            
            if (!v.checkValidation("text", txtRegisterUserName.getText()))
                errorMsg += "User Name supports only Character \n";   
            
            if(!v.checkValidation("email", txtRegisterUserEmail.getText()))
                errorMsg += "Only Valid Email \n";            
        }
      if(errorMsg.isEmpty()){  
          
        user = new UserOF();
        user.setUser_id(0);      
        user.setUser_name(txtRegisterUserName.getText());      
        user.setUser_password( new String(txtRegisterUserPassword.getPassword()));
        user.setUser_email(txtRegisterUserEmail.getText());
        user.setUser_type(cmbRegisterUserType.getSelectedItem().toString());
        blUser = new UserBl(user);

        if(blUser.insertUser()){
          JOptionPane.showMessageDialog(this, "User Created Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
        }else{
          JOptionPane.showMessageDialog(this, "Unable to add user", "Error Occured", JOptionPane.ERROR_MESSAGE);
        }
        
      }else{
          JOptionPane.showMessageDialog(this, errorMsg, "Error Occured", JOptionPane.ERROR_MESSAGE);
      }
      
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
     
     //dispose();
}//GEN-LAST:event_btnRegisterUserActionPerformed

private void btnResetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetUserActionPerformed
// TODO add your handling code here:
    txtRegisterUserName.setText("");
    txtRegisterUserPassword.setText("");
    txtRegisterUserEmail.setText("");
    cmbRegisterUserType.setSelectedItem("");
}//GEN-LAST:event_btnResetUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JButton btnResetUser;
    private javax.swing.JComboBox cmbRegisterUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtRegisterUserEmail;
    private javax.swing.JTextField txtRegisterUserName;
    private javax.swing.JPasswordField txtRegisterUserPassword;
    // End of variables declaration//GEN-END:variables
    private UserBl blUser;
    private UserOF user;
}
