package Interface;

import Executor.CategoryEx;
import Object.CategoryObj;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahat
 * category list display
 */
public class CategoryList extends javax.swing.JInternalFrame {

    /** Creates new form CategoryList */
    public CategoryList() {
        initComponents();
        category = new CategoryObj();
        blcategory = new CategoryEx();
        DefaultTableModel dtm = new DefaultTableModel();
        try{

            dtm.addColumn("Category Id");
            dtm.addColumn("Category Name");
            dtm.addColumn("Category Detail");
                        
            ArrayList<CategoryObj> categorys = blcategory.getcategoryList();
            for(int i=0; i<categorys.size(); ++i ){
              Object[] data = { categorys.get(i).getCatId(), categorys.get(i).getCatName(), categorys.get(i).getCatDetail() };
              dtm.addRow(data);
            }
            tblCategoryList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategoryList = new javax.swing.JTable();
        btnEditSelected = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCategoryId = new javax.swing.JTextField();
        txtCategoryName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCategoryDetail = new javax.swing.JTextArea();
        btnCategoryUpdate = new javax.swing.JButton();
        btnCategoryDelete = new javax.swing.JButton();
        txtSearchCategory = new javax.swing.JTextField();
        btnSearchCategory = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Category List");
        setPreferredSize(new java.awt.Dimension(870, 575));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Category List ");

        tblCategoryList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblCategoryList);

        btnEditSelected.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditSelected.setText("Edit/delete Selected Category");
        btnEditSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSelectedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Edit The Selected Category");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Category Id : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Category Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Category Detail : ");

        txtCategoryId.setEditable(false);

        txtCategoryDetail.setColumns(20);
        txtCategoryDetail.setRows(5);
        jScrollPane2.setViewportView(txtCategoryDetail);

        btnCategoryUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCategoryUpdate.setText("Update");
        btnCategoryUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryUpdateActionPerformed(evt);
            }
        });

        btnCategoryDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCategoryDelete.setText("Delete");
        btnCategoryDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryDeleteActionPerformed(evt);
            }
        });

        btnSearchCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchCategory.setText("Search");
        btnSearchCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCategoryActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Category.png"))); // NOI18N
        jLabel6.setText("jLabel4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Update Category Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(63, 63, 63)
                                        .addComponent(btnEditSelected))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCategoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtCategoryId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCategoryName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSearchCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchCategory))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCategoryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addComponent(btnCategoryUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCategoryDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnEditSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectedActionPerformed
// TODO add your handling code here:
    txtCategoryId.setText(tblCategoryList.getModel().getValueAt(tblCategoryList.getSelectedRow(), 0).toString());
    txtCategoryName.setText(tblCategoryList.getModel().getValueAt(tblCategoryList.getSelectedRow(), 1).toString());
    txtCategoryDetail.setText(tblCategoryList.getModel().getValueAt(tblCategoryList.getSelectedRow(), 2).toString());    
}//GEN-LAST:event_btnEditSelectedActionPerformed

private void btnCategoryUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryUpdateActionPerformed
// TODO add your handling code here:
    try{
       category = new CategoryObj();
       category.setCatId(Integer.parseInt(txtCategoryId.getText()));
       category.setCatName( new String(txtCategoryName.getText())); 
       category.setCatDetail( new String(txtCategoryDetail.getText()));
       blcategory = new CategoryEx(category);
       if(blcategory.updatecategory()){
           JOptionPane.showMessageDialog(this, "Category Updated Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           DashBoardAdm.dashBoard.add( new CategoryList());
           
       }else{
           JOptionPane.showMessageDialog(this, "Unable to Update Category", "Error Occured", JOptionPane.ERROR_MESSAGE);
       }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCategoryUpdateActionPerformed

private void btnCategoryDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryDeleteActionPerformed
// TODO add your handling code here:
    try{
        category = new CategoryObj();
        category.setCatId(Integer.parseInt(txtCategoryId.getText()));
        blcategory = new CategoryEx(category);
        if(blcategory.deletecategory()){
            JOptionPane.showMessageDialog(this, "Category Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            DashBoardAdm.dashBoard.add( new CategoryList());
        }else{
            JOptionPane.showMessageDialog(this, "Unabale to Delete Category", "Error Occured", JOptionPane.ERROR_MESSAGE );
        }
    }catch( Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnCategoryDeleteActionPerformed

private void btnSearchCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCategoryActionPerformed
// TODO add your handling code here:
    try{
            category.setCatName(txtSearchCategory.getText());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Category Id");
            dtm.addColumn("Category Name");
            dtm.addColumn("Category Detail");            
            
            blcategory = new CategoryEx(category);
            ArrayList<CategoryObj> categorys = blcategory.searchcategory();
                if(categorys.size() > 0){
                    for( int i=0; i<categorys.size(); i++){
                        Object[] data = { categorys.get(i).getCatId(), categorys.get(i).getCatName(), categorys.get(i).getCatDetail() };
                        dtm.addRow(data);                    
                    }
                    tblCategoryList.setModel(dtm);
                
                } else {
                    Object[] data = {"","","",""};
                    JOptionPane.showMessageDialog(this, "No Category FOund");
                    tblCategoryList.setModel(dtm);
                }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }
}//GEN-LAST:event_btnSearchCategoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoryDelete;
    private javax.swing.JButton btnCategoryUpdate;
    private javax.swing.JButton btnEditSelected;
    private javax.swing.JButton btnSearchCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCategoryList;
    private javax.swing.JTextArea txtCategoryDetail;
    private javax.swing.JTextField txtCategoryId;
    private javax.swing.JTextField txtCategoryName;
    private javax.swing.JTextField txtSearchCategory;
    // End of variables declaration//GEN-END:variables
    private CategoryObj category;
    private CategoryEx blcategory;
}
