package Interface;

import Executor.CategoryEx;
import Executor.ItemEx;
import Executor.SupplierEx;
import Object.CategoryObj;
import Object.ItemObj;
import Object.SupplierObj;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahat
 * item list and update form
 */
public class ItemRegister extends javax.swing.JInternalFrame {

    /** Creates new form ItemRegister */
    public ItemRegister() {
        initComponents();
      
      // Get category name in comobox  
      CategoryEx catBl = new CategoryEx();
      try {          
           ArrayList<CategoryObj> catName = catBl.getcategoryList();
           for(int i=0; i<catName.size(); ++i )           
           {     
             cmbCategory.addItem(catName.get(i).getCatName());             
           }
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "No Category Name.\n" + e);
      }
      
      // Get supplier name in combo box
      SupplierEx supBl = new SupplierEx();
      try {          
           ArrayList<SupplierObj> supplierName = supBl.getsupplierList();
           for(int i=0; i<supplierName.size(); ++i )           
           {     
             cmbSupplier.addItem(supplierName.get(i).getsupplierName());             
           }
      }catch(Exception e){
          JOptionPane.showMessageDialog(this, "No Supplier Name.\n" + e);
      }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemRate = new javax.swing.JTextField();
        txtItemQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemOrderDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtItemDetail = new javax.swing.JTextArea();
        btnItemRegister = new javax.swing.JButton();
        btnItemReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox();
        cmbSupplier = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtItemSuppliedDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Item Register Form");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Register New Item");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Item Name  : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Item Rate  : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Item Quantity  : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Item Order Date  : ");

        txtItemOrderDate.setDateFormatString("yyyy-MM-dd");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Item Supplied Date  : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Item Detail  : ");

        txtItemDetail.setColumns(20);
        txtItemDetail.setRows(5);
        jScrollPane1.setViewportView(txtItemDetail);

        btnItemRegister.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnItemRegister.setText("Register");
        btnItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemRegisterActionPerformed(evt);
            }
        });

        btnItemReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnItemReset.setText("Reset");
        btnItemReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemResetActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Category Name  : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Supplier Name  : ");

        txtItemSuppliedDate.setDateFormatString("yyyy-MM-dd");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Item.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnItemRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemOrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemQuantity)
                            .addComponent(txtItemRate)
                            .addComponent(cmbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCategory, 0, 254, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtItemRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtItemQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(txtItemOrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtItemSuppliedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnItemRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnItemReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemRegisterActionPerformed
// TODO add your handling code here:
    try{
        
        String errorMsg = "";
        if("".equals(txtItemName.getText())){
          errorMsg +=  "Item Name cannot be empty \n";
        }
        if("".equals(txtItemRate.getText())){
          errorMsg +=  "Item Rate cannot be empty \n";
        }
        if("".equals(txtItemQuantity.getText())){
          errorMsg += "Item Quantity cannot be emty \n";
        }        
        
        else{
            Validation v = new Validation();
            
            if (!v.checkValidation("text", txtItemName.getText()))
                errorMsg += "Item Name supports only Character \n";                           
            if (!v.checkValidation("number", txtItemRate.getText()))
                errorMsg += "Item Rate supports only Number \n";
            if (!v.checkValidation("number", txtItemQuantity.getText()))
                errorMsg += "Item Quantity supports only Number \n";            
                           
        }
      if(errorMsg.isEmpty()){  
        
        item = new ItemObj();
        item.setItemId(0);
        item.setitemName(txtItemName.getText());

        item.setitemRate(Integer.parseInt(txtItemRate.getText()));
        item.setitemQuantity(Integer.parseInt(txtItemQuantity.getText()));

        Date od = txtItemOrderDate.getDate();
        SimpleDateFormat order_date =new SimpleDateFormat("yyyy-MM-dd");
        item.setitemOrderDate(order_date.format(od).toString());

        Date sd = txtItemSuppliedDate.getDate();
        SimpleDateFormat supplied_date = new SimpleDateFormat("yyyy-MM-dd");
        item.setitemSuppliedDate(supplied_date.format(sd).toString());

       //user.setuserType(cmbRegisterUserType.getSelectedItem().toString());
        item.setCatName(cmbCategory.getSelectedItem().toString());
        item.setsupplierName(cmbSupplier.getSelectedItem().toString());

        item.setitemDetail(txtItemDetail.getText());

        blItem = new ItemEx(item);
        if(blItem.insertItem()){
          JOptionPane.showMessageDialog(this, "Item Created Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
        }else{
          JOptionPane.showMessageDialog(this, "Unable to add Item", "Error Occured", JOptionPane.ERROR_MESSAGE);
        }
      
      }else{
          JOptionPane.showMessageDialog(this, errorMsg, "Error Occured", JOptionPane.ERROR_MESSAGE);
      } 
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured here", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnItemRegisterActionPerformed

private void btnItemResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemResetActionPerformed
// TODO add your handling code here:
    txtItemName.setText("");
    cmbCategory.setSelectedIndex(0);
    cmbSupplier.setSelectedIndex(0);    
    txtItemRate.setText("");
    txtItemQuantity.setText("");
    txtItemOrderDate.setDate(null);
    txtItemSuppliedDate.setDate(null);
    txtItemDetail.setText("");
    
}//GEN-LAST:event_btnItemResetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnItemRegister;
    private javax.swing.JButton btnItemReset;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtItemDetail;
    private javax.swing.JTextField txtItemName;
    private com.toedter.calendar.JDateChooser txtItemOrderDate;
    private javax.swing.JTextField txtItemQuantity;
    private javax.swing.JTextField txtItemRate;
    private com.toedter.calendar.JDateChooser txtItemSuppliedDate;
    // End of variables declaration//GEN-END:variables
    private ItemEx blItem;
    private ItemObj item;
}
