/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReturnList.java
 *
 * Created on Jun 27, 2015, 1:00:07 PM
 */
package Interface;

import Executor.ItemEx;
import Executor.ReturnEx;
import Databse.GlobalConnection;
import Object.ItemObj;
import Object.ReturnObj;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahat
 */
public class ReturnList extends javax.swing.JInternalFrame {
    
    GlobalConnection db = new GlobalConnection();
    ArrayList<String> ar = new ArrayList<String>();
    
    /** Creates new form ReturnList */
    public ReturnList(){
        initComponents();
        
        // item name in combo box
        ItemEx it = new ItemEx();
        try{
            ArrayList<ItemObj> itm = it.getItemList();
            for( int i=0; i<itm.size(); ++i){
                cmbItemName.addItem(itm.get(i).getitemName());
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        rturn = new ReturnObj();
        blRturn = new ReturnEx();
        DefaultTableModel dtm = new DefaultTableModel();
        
        try{
            dtm.addColumn("Return Id");
            dtm.addColumn("Return Name");
            dtm.addColumn("Return Quantity");            
            dtm.addColumn("Return Date");
            dtm.addColumn("Item Name");
            
            ArrayList<ReturnObj> rturn = blRturn.getRturnList();
            for(int i=0; i<rturn.size(); ++i ){
              Object[] data = { rturn.get(i).getreturnId(), rturn.get(i).getreturnName() ,rturn.get(i).getreturnQuantity(), rturn.get(i).getreturnDate(), rturn.get(i).getitemName() };
              dtm.addRow(data);
            }
            tblReturnList.setModel(dtm);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        } 
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtReturnSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReturnList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemReturnQuantity = new javax.swing.JTextField();
        cmbItemName = new javax.swing.JComboBox();
        txtItemReturnDate = new com.toedter.calendar.JDateChooser();
        btnReturnUpdate = new javax.swing.JButton();
        btnReturnDelete = new javax.swing.JButton();
        btnReturnSearch = new javax.swing.JButton();
        btnSelectedReturn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtReturnId = new javax.swing.JTextField();
        txtReturnName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Return Items List");

        tblReturnList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblReturnList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit Return Item Detail");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Item Retun Date : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Retun Item Quantity : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Item Name : ");

        txtItemReturnDate.setDateFormatString("yyyy-MM-dd");

        btnReturnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturnUpdate.setText("Update");
        btnReturnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnUpdateActionPerformed(evt);
            }
        });

        btnReturnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturnDelete.setText("Delete");
        btnReturnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnDeleteActionPerformed(evt);
            }
        });

        btnReturnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturnSearch.setText("Search");
        btnReturnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnSearchActionPerformed(evt);
            }
        });

        btnSelectedReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectedReturn.setText("Edit/delete Selected Item");
        btnSelectedReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedReturnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Return Id : ");

        txtReturnId.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Return Name : ");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Return.png"))); // NOI18N
        jLabel8.setText("jLabel6");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Update Returned Item Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(btnSelectedReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9))
                            .addComponent(txtReturnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147)
                        .addComponent(btnReturnSearch))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(91, 91, 91))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(txtItemReturnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtReturnName, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(txtReturnId, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtItemReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReturnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(btnReturnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnReturnSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReturnId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtReturnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(btnSelectedReturn)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtReturnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtItemReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtItemReturnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnReturnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnReturnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSelectedReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedReturnActionPerformed
// TODO add your handling code here: 
   try{
        String rId    = tblReturnList.getValueAt(tblReturnList.getSelectedRow(), 0).toString();
        String rName  = tblReturnList.getValueAt(tblReturnList.getSelectedRow(), 1).toString();
        String rQty   = tblReturnList.getValueAt(tblReturnList.getSelectedRow(), 2).toString();
        String rDate  = tblReturnList.getValueAt(tblReturnList.getSelectedRow(), 3).toString();
        String itemName  = tblReturnList.getValueAt(tblReturnList.getSelectedRow(), 4).toString();
        
        txtReturnId.setText(rId);
        txtReturnName.setText(rName);
        txtItemReturnQuantity.setText(rQty);
   
        // Date load in edit form
        SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd");
        txtItemReturnDate.setDate((Date)oFormat.parse(rDate));
  
        cmbItemName.setSelectedItem(itemName);
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
        
}//GEN-LAST:event_btnSelectedReturnActionPerformed

private void btnReturnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnUpdateActionPerformed
// TODO add your handling code here:
    try {
       rturn = new ReturnObj();
       rturn.setreturnId(Integer.parseInt(txtReturnId.getText()));
       rturn.setreturnName(txtReturnName.getText());
       rturn.setreturnQuantity( Integer.parseInt(txtItemReturnQuantity.getText())); 
       
       Date dtt = txtItemReturnDate.getDate();
       SimpleDateFormat ftt = new SimpleDateFormat("yyyy-MM-dd");
       rturn.setreturnDate(ftt.format(dtt).toString());
       
       rturn.setitemName(cmbItemName.getSelectedItem().toString());
       
       blRturn = new ReturnEx(rturn);   
       if(blRturn.updateRturn()){
           JOptionPane.showMessageDialog(this, "Return Item Updated Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           DashBoardAdm.dashBoard.add( new CategoryList());
           
            }else{
                JOptionPane.showMessageDialog(this, "Unable to Update Return Item", "Error Occured", JOptionPane.ERROR_MESSAGE);
            }
       
     }catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
     }
    
}//GEN-LAST:event_btnReturnUpdateActionPerformed

private void btnReturnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnDeleteActionPerformed
// TODO add your handling code here:
    try{
        rturn = new ReturnObj();
        rturn.setreturnId(Integer.parseInt(txtReturnId.getText()));
        blRturn = new ReturnEx(rturn);
        if(blRturn.deleteRturn()){
            JOptionPane.showMessageDialog(this, "Return Item Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            DashBoardAdm.dashBoard.add( new CategoryList());
        }else{
            JOptionPane.showMessageDialog(this, "Unabale to Delete Return Item", "Error Occured", JOptionPane.ERROR_MESSAGE );
        }
    }catch( Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnReturnDeleteActionPerformed

private void btnReturnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnSearchActionPerformed
// TODO add your handling code here:
        try{
            rturn.setreturnName(txtReturnSearch.getText().toString());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Return Id");
            dtm.addColumn("Return Name");
            dtm.addColumn("Return Quantity");            
            dtm.addColumn("Return Date");
            dtm.addColumn("Item Name");
           
            blRturn = new ReturnEx(rturn);
            ArrayList<ReturnObj>rturns = blRturn.searchRturn();
                if(rturns.size() > 0){
                    for( int i=0; i<rturns.size(); i++){
                        Object[] data = { rturns.get(i).getreturnId(), rturns.get(i).getreturnName() ,rturns.get(i).getreturnQuantity(),rturns.get(i).getreturnDate(),rturns.get(i).getitemName(),};
                        dtm.addRow(data);                    
                    }
                    tblReturnList.setModel(dtm);
                
                }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }
}//GEN-LAST:event_btnReturnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnDelete;
    private javax.swing.JButton btnReturnSearch;
    private javax.swing.JButton btnReturnUpdate;
    private javax.swing.JButton btnSelectedReturn;
    private javax.swing.JComboBox cmbItemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReturnList;
    private com.toedter.calendar.JDateChooser txtItemReturnDate;
    private javax.swing.JTextField txtItemReturnQuantity;
    private javax.swing.JTextField txtReturnId;
    private javax.swing.JTextField txtReturnName;
    private javax.swing.JTextField txtReturnSearch;
    // End of variables declaration//GEN-END:variables
    private ReturnObj rturn;
    private ReturnEx blRturn;
}
