package Interface;

import Executor.ItemEx;
import Executor.SalesEx;
import Databse.GlobalConnection;
import Object.ItemObj;
import Object.SalesObj;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahat
 * sales list form
 */
public class SalesList extends javax.swing.JInternalFrame {
    
    GlobalConnection db = new GlobalConnection();
    ArrayList<String> ar = new ArrayList<String>();
    
    /** Creates new form SalesList */
    public SalesList() {
        initComponents();
        
        // item name in combo box
        ItemEx it = new ItemEx();
        try{
            ArrayList<ItemObj> itm = it.getItemList();
            for( int i=0; i<itm.size(); ++i){
                cmbItemName.addItem(itm.get(i).getitemName());
            }
        
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        sale = new SalesObj();
        blsale = new SalesEx();
        DefaultTableModel dtm = new DefaultTableModel();
        try{
            dtm.addColumn("Id");
            dtm.addColumn("Customer Name");
            dtm.addColumn("Customer Address");
            dtm.addColumn("Date");
            dtm.addColumn("Bill No");
            dtm.addColumn("Rate");
            dtm.addColumn("Quantity");
            dtm.addColumn("Item Name");
                                    
            ArrayList<SalesObj> sales = blsale.getSalesList();
            for(int i=0; i<sales.size(); ++i ){
              Object[] data = { sales.get(i).getsalesId(), sales.get(i).getsalesCustomerName(), sales.get(i).getsalesCustomerAddress(), sales.get(i).getsalesDate(), sales.get(i).getsalesBillNo(), sales.get(i).getsalesRate(), sales.get(i).getsalesQuantity(), sales.get(i).getitemName() };
              dtm.addRow(data);
            }
            tblSalesList.setModel(dtm);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearchCustomerName = new javax.swing.JTextField();
        btnSalesSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesList = new javax.swing.JTable();
        btnSelectedSales = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSalesId = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        txtBillNo = new javax.swing.JTextField();
        txtSaleRate = new javax.swing.JTextField();
        txtSaleQuantity = new javax.swing.JTextField();
        btnSalesUpdate = new javax.swing.JButton();
        btnSalesDelete = new javax.swing.JButton();
        cmbItemName = new javax.swing.JComboBox();
        txtSalesDate = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Sales List");
        setPreferredSize(new java.awt.Dimension(1100, 622));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sales Detail List ");

        btnSalesSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalesSearch.setText("Search Sales");
        btnSalesSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesSearchActionPerformed(evt);
            }
        });

        tblSalesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblSalesList);

        btnSelectedSales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelectedSales.setText("Edit/delete Selected Sales");
        btnSelectedSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectedSalesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Selected Sales Detail");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Unique Sale Id : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Customer Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Customer Address : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sales Date : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bill No : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sales Rate : ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Sales Quantity : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Item Name : ");

        txtSalesId.setEditable(false);

        btnSalesUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalesUpdate.setText("Update");
        btnSalesUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesUpdateActionPerformed(evt);
            }
        });

        btnSalesDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalesDelete.setText("Delete");
        btnSalesDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesDeleteActionPerformed(evt);
            }
        });

        cmbItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemNameActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Sales.png"))); // NOI18N
        jLabel11.setText("jLabel9");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Update Sales Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearchCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(110, 110, 110)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSelectedSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalesSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSaleRate)
                                    .addComponent(txtBillNo)
                                    .addComponent(txtSaleQuantity)
                                    .addComponent(cmbItemName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalesUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSalesDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustomerAddress)
                                    .addComponent(txtCustomerName)
                                    .addComponent(txtSalesId)
                                    .addComponent(txtSalesDate, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))))))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalesSearch))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSelectedSales)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalesId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtCustomerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtSalesDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaleRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSaleQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalesUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalesDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemNameActionPerformed
// TODO add your handling code here:
  
}//GEN-LAST:event_cmbItemNameActionPerformed

private void btnSelectedSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectedSalesActionPerformed
// TODO add your handling code here:
  try{
    
    String saleId    = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 0).toString();
    String custName  = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 1).toString();
    String custAdd   = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 2).toString();
    String saleDate  = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 3).toString();
    String saleBill  = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 4).toString();
    String saleRate  = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 5).toString();
    String saleQty   = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 6).toString();
    String itemName  = tblSalesList.getValueAt(tblSalesList.getSelectedRow(), 7).toString();
        
    txtSalesId.setText(saleId);
    txtCustomerName.setText(custName);
    txtCustomerAddress.setText(custAdd);
    
    // Date load in edit form
    SimpleDateFormat oFormat = new SimpleDateFormat("yyyy-MM-dd");
    txtSalesDate.setDate((Date)oFormat.parse(saleDate));
   
    txtBillNo.setText(saleBill);
    txtSaleRate.setText(saleRate);
    txtSaleQuantity.setText(saleQty);
    cmbItemName.setSelectedItem(itemName);
    
    }catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
    
}//GEN-LAST:event_btnSelectedSalesActionPerformed

private void btnSalesUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesUpdateActionPerformed
// TODO add your handling code here:
    
    try {
       sale = new SalesObj();
       sale.setsalesId(Integer.parseInt(txtSalesId.getText()));
       sale.setsalesCustomerName( new String(txtCustomerName.getText())); 
       sale.setsalesCustomerAddress( new String(txtCustomerAddress.getText()));
       
       Date dtt = txtSalesDate.getDate();
       SimpleDateFormat ftt = new SimpleDateFormat("yyyy-MM-dd");
       sale.setsalesDate(ftt.format(dtt).toString());

       sale.setsalesBillNo(Integer.parseInt(txtBillNo.getText()));
       sale.setsalesRate(Integer.parseInt(txtSaleRate.getText()));
       sale.setsalesQuantity(Integer.parseInt(txtSaleQuantity.getText()));
       sale.setitemName(cmbItemName.getSelectedItem().toString());
       
       blsale = new SalesEx(sale);   
       if(blsale.updateSales()){
           JOptionPane.showMessageDialog(this, "Sales Updated Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
           DashBoardAdm.dashBoard.add( new CategoryList());
           
            }else{
                JOptionPane.showMessageDialog(this, "Unable to Update Sales", "Error Occured", JOptionPane.ERROR_MESSAGE);
            }
       
       } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
       }
    
}//GEN-LAST:event_btnSalesUpdateActionPerformed

    private void btnSalesSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesSearchActionPerformed
        // TODO add your handling code here:
        try{
            sale.setsalesCustomerName(txtSearchCustomerName.getText());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Id");
            dtm.addColumn("Customer Name");            
            dtm.addColumn("Customer Address");
            dtm.addColumn("Date");
            dtm.addColumn("Bill No");
            dtm.addColumn("Rate");
            dtm.addColumn("Quantity");
            dtm.addColumn("Item Name");            
           
            blsale = new SalesEx(sale);
            ArrayList<SalesObj>sls = blsale.searchSales();
                if(sls.size() > 0){
                    for( int i=0; i<sls.size(); i++){
                        Object[] data = { sls.get(i).getsalesId(), sls.get(i).getsalesCustomerName(),  sls.get(i).getsalesCustomerAddress(), sls.get(i).getsalesDate(), sls.get(i).getsalesBillNo(), sls.get(i).getsalesRate(), sls.get(i).getsalesQuantity(),sls.get(i).getitemName() };
                        dtm.addRow(data);                    
                    }
                    tblSalesList.setModel(dtm);
                
                }
                else{
                   Object[] date = {"","","","","","","",""};
                   JOptionPane.showMessageDialog(this, "No Sales Item FOund");
                   tblSalesList.setModel(dtm);
                }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }
    }//GEN-LAST:event_btnSalesSearchActionPerformed

    private void btnSalesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesDeleteActionPerformed
        // TODO add your handling code here:
        try{
            sale = new SalesObj();
            sale.setsalesId(Integer.parseInt(txtSalesId.getText()));
            blsale = new SalesEx(sale);
            if(blsale.deleteSales()){
                JOptionPane.showMessageDialog(this, "Sales Item Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                DashBoardAdm.dashBoard.add( new CategoryList());
            }else{
                JOptionPane.showMessageDialog(this, "Unabale to Delete Sales Item", "Error Occured", JOptionPane.ERROR_MESSAGE );
            }
        }catch( Exception ex){
            JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalesDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalesDelete;
    private javax.swing.JButton btnSalesSearch;
    private javax.swing.JButton btnSalesUpdate;
    private javax.swing.JButton btnSelectedSales;
    private javax.swing.JComboBox cmbItemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalesList;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtSaleQuantity;
    private javax.swing.JTextField txtSaleRate;
    private com.toedter.calendar.JDateChooser txtSalesDate;
    private javax.swing.JTextField txtSalesId;
    private javax.swing.JTextField txtSearchCustomerName;
    // End of variables declaration//GEN-END:variables
    private SalesObj sale;
    private SalesEx blsale;
}
