package Interface;

import Executor.UserEx;
import Object.UserObj;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rahat
 * user list and update/delete form
 */
public class UserList extends javax.swing.JInternalFrame {

    /** Creates new form UserList */
    public UserList() {
        initComponents();
        user = new UserObj();
        blUser = new UserEx();
        DefaultTableModel dtm = new DefaultTableModel();
        try{

            dtm.addColumn("User Id");
            dtm.addColumn("User Name");
            //dtm.addColumn("User Password");
            dtm.addColumn("User Email");
            dtm.addColumn("User Type");

            ArrayList<UserObj> users = blUser.getUserList();
            for(int i=0; i<users.size(); ++i ){
              Object[] data = { users.get(i).getuserId(), users.get(i).getuserName(),/*  users.get(i).getuserPassword(),*/ users.get(i).getuserEmail(), users.get(i).getuserType()};
              dtm.addRow(data);
            }
            tblUsersList.setModel(dtm);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    
    public UserObj getUser() {
        return user;
    }

    public void setUser(UserObj user) {
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnEditSelectedUser = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox();
        btnUserUpdate = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtUserSearch = new javax.swing.JTextField();
        btnUserSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Update Users List ");
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(925, 557));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Edit Selected User's Detail");

        btnEditSelectedUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditSelectedUser.setText("Edit/Delete Selected User");
        btnEditSelectedUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSelectedUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("User Name : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("User Email : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("User Type : ");

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Admin" }));
        cmbUserType.setToolTipText("");
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        btnUserUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserUpdate.setText("Update");
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });

        btnUserDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserDelete.setText("Delete");
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Unique User Id : ");

        txtUserSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserSearchKeyReleased(evt);
            }
        });

        btnUserSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserSearch.setText("Search");
        btnUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSearchActionPerformed(evt);
            }
        });

        tblUsersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsersList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Users List ");

        txtUserId.setEditable(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/User.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Update User Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addComponent(btnEditSelectedUser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(btnUserUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUserSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditSelectedUser)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUserUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnUserDelete)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnEditSelectedUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectedUserActionPerformed
// TODO add your handling code here:
    txtUserId.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 0).toString());
    txtUserName.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 1).toString());
    txtUserEmail.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 2).toString());
    cmbUserType.setSelectedItem(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 3).toString());
}//GEN-LAST:event_btnEditSelectedUserActionPerformed

private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
// TODO add your handling code here:
    try{
      user = new UserObj();
      user.setuserId(Integer.parseInt(txtUserId.getText()));
      user.setuserName( new String(txtUserName.getText()));
      user.setuserEmail( new String(txtUserEmail.getText()));
      user.setuserType(cmbUserType.getSelectedItem().toString());
      blUser = new UserEx(user);
      if(blUser.updateUser()){
        JOptionPane.showMessageDialog(this, "User Updated Successfully", "Operation Successful", JOptionPane.INFORMATION_MESSAGE);
      
        this.dispose();
        DashBoardAdm.dashBoard.add( new UserList());
      }else{
        JOptionPane.showMessageDialog(this, "Unable to update user", "Error Occured", JOptionPane.ERROR_MESSAGE);
      }
    }catch(Exception ex){
      JOptionPane.showMessageDialog(this, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnUserUpdateActionPerformed

private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
// TODO add your handling code here:
    try{
        user = new UserObj();
        user.setuserId(Integer.parseInt(txtUserId.getText()));
        blUser = new UserEx(user);
        if(blUser.deleteUser()){
            JOptionPane.showMessageDialog(this, "User Deleted Successfully", "Operation Successfull", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            DashBoardAdm.dashBoard.add( new UserList());
        }else{
            JOptionPane.showMessageDialog(this, "Unabale to Delete User", "Error Occured", JOptionPane.ERROR_MESSAGE );
        }
    }catch( Exception ex){
        JOptionPane.showMessageDialog(this,ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnUserDeleteActionPerformed

private void txtUserSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserSearchKeyReleased
// TODO add your handling code here
//    try{
//      user = new UserObj();
//      user.setuserId(Integer.parseInt(txtUserId.getText()));
//      user.setuserName( new String(txtUserName.getText()));
//      user.setuserEmail( new String(txtUserEmail.getText()));
//      user.setuserType(cmbUserType.getSelectedItem().toString());
//      blUser = new UserEx(user);
//      ArrayList<UserOF> users = blUser.searchUser();
//        for(int i=0; i<users.size(); ++i ){
//          Object[] data = { users.get(i).getuserId(), users.get(i).getuserName(), users.get(i).getuserEmail(), users.get(i).getuserType()};
//            txtUserId.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 0).toString());
//            txtUserName.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 1).toString());
//            txtUserEmail.setText(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 2).toString());
//            cmbUserType.setSelectedItem(tblUsersList.getModel().getValueAt(tblUsersList.getSelectedRow(), 3).toString());
//        }
//    }catch(Exception ex){
//      JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);
//    }
}//GEN-LAST:event_txtUserSearchKeyReleased

private void btnUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSearchActionPerformed
// TODO add your handling code here:        
        //initComponents();
        try{
            user.setuserName(txtUserSearch.getText());
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("User Id");
            dtm.addColumn("User Name");
            dtm.addColumn("User Email");
            dtm.addColumn("User Type");
            
            blUser = new UserEx(user);
            ArrayList<UserObj> users = blUser.searchUser();
                if(users.size() > 0){
                    for( int i=0; i<users.size(); i++){
                        Object[] data = { users.get(i).getuserId(), users.get(i).getuserName(), users.get(i).getuserEmail(), users.get(i).getuserType()};
                        dtm.addRow(data);                    
                    }
                    tblUsersList.setModel(dtm);
                
                } else {
                    Object[] data = {"","","",""};
                    JOptionPane.showMessageDialog(this, "NO user FOund");
                    tblUsersList.setModel(dtm);
                }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);        
        }                
}//GEN-LAST:event_btnUserSearchActionPerformed

private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmbUserTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditSelectedUser;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserSearch;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsersList;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtUserSearch;
    // End of variables declaration//GEN-END:variables
    private UserObj user;
    private UserEx blUser;
    
}
